### ISSUE TITLE
ef033u1 export

### ISSUE THREAD

**Issue by asudau** [asudau/Promovierendenverwaltung#102]
ich glaub für diesen export-wert hab ich noch nicht korrekt umgesetzt was damit passiert, wenn er nicht ausgefüllt werden muss weil der HZB in deutschland erreicht wurde. Der hängt nämlich derzeit offenbar noch an hzb_statt

**Comment by adedden** [comment]
Bundesland_astat ist gleich 99, wenn nicht in Deutschland (HZB_Arten in der Liste definiert)
