### ISSUE TITLE
Verwirrende Bezeichnung austauschen

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#104]
Hallo Annelene,

Alle Felder die "unter Bedingung" augefüllt werden müssen, würde ich wenn leer bezeichnen als "ggf. auswählen" anstatt "nicht erforderlich", weil "nicht erforderlich" nicht stimmt, wenn sie doch ausgefüllt werden müssen. Dies gilt für die folgenden Felder:
Daten zur Promotion: Ende der Promotion - Monat
Daten zur ErstEin - Staat
Daten zur Prom ber Abschl - Staat
Daten zur HZB - Bundesland, Kreis **und** Staat

Beste Grüße
Anne

**Comment by asudau** [comment]
die idee dahinter war, das wenn sie nicht editierbar sind nicht drin steht ggf. ausfüllen.. da sich diese formulierungen aber schwer dynamisch ändern lassen werde ich es so machen wie du vorschlägst!
