### ISSUE TITLE
aktivierte Plichtfelder direkt kennzeichnen

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#108]
Felder, die unter Bedingung Pflichtfelder sind (default ausgegraut), müssen wenn sie "aktiviert sind", als Pflichfeld gekennzeichnet sein (Fett mit Sternchen). Im Moment findet diese Kennzeichnung erst statt nachdem der Fall gespeichert wird und danach wieder geöffnet. 

Ich weiß nicht, wie technisch schwierig diese Anforderung ist umzusetzen. Falls es viel Zeit kosten würde, sollen wir diese Anforderung nicht umsetzen.

**Comment by asudau** [comment]
ja an den thema war ich gestern schon dran, hab noch nicht aufgegeben ;-)
