### ISSUE TITLE
Bedingte Pflichtfelder "demarkieren" nachdem sie ausgefüllt werden sind

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#109]
Wenn bedingte Pflichtfelder ausgefüllt worden sind, sollen sie nicht mehr fett dargestellt werden (siehe Beispielfall "Benno Dedden")

Sind die gleiche Felder als in #108

**Comment by asudau** [comment]
sollte jetzt passen siehe #108
