### ISSUE TITLE
Statusberechnung (Pflichtfeldsetzung) nicht richtig für importierten Fälle

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#111]
Beispiel: Heike von Dahlern

Dieser Fall hat Status 103%, obwohl nicht alle Pflichtfelder gefüllt sind?

Und ich sehe mehrere Probleme bzgl. der Pflichtfelder:
- Daten zur Promotion - Teilnahme an einem strukturierenden Promotionsprogramm ist gekennzeichnet als nicht ausgefüllt, obwohl hier ein Wert ausgefüllt ist
- Daten zur Promotion - Promotionsbeginn - Monat: ist nicht gekennzeichnet als Pflichtfeld 
- Daten zur Promotion berechtigenden Abschlussprüfung - Monat des Prüfungsabschlusses: ist nicht gekennzeichnet als Pflichtfeld

Wäre es vielleicht eine Idee Status als Anzahl der nicht ausgefüllte Pflichtfelder zu definieren? Dies ist vielleicht einfacher technisch umzusetzen und intuitiver zu verstehen für Anwender?

**Comment by asudau** [comment]
huhu, an der status geschichte bin ich noch dran.. das betrifft derzeit potentiell alle einträge

**Comment by asudau** [comment]
fixed in #108
