### ISSUE TITLE
Promotionsbeginn - Monat noch kein Pflichtfeld

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#115]
Für den Fall "Wilfred Asampambila Agana" ist Promotionsbeginn-Monat noch kein Pflichtfeld? Es wird nicht rot, obwohl es nicht ausgefüllt ist.

**Comment by asudau** [comment]
das war ein fehler in der anzeige, der wert war tatsächlich gesetzt (erinnerung für mich: value_key für monatsfelder muss his_id sein nicht id)
