### ISSUE TITLE
Promotionsfächer-Liste bereinigen

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#117]
Sonja liefert eine aktualisierte Liste der Promotionsfächer an, diese muss hochgespielt werden.

**Comment by sonschul** [comment]
Anbei die bereinigte Liste mit möglichen Promotionsfächern:

[Promotionsfaecher.xlsx](https://github.com/asudau/Promovierendenverwaltung/files/2491418/Promotionsfaecher.xlsx)

**Comment by asudau** [comment]
ist ausgetauscht
