### ISSUE TITLE
Import aktualisieren - Ergänzung mit Promotions-Endedatum

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#118]
Die Import wird durch ZBW nochmal ergänzt mit Promotionsendedatum (Monat und Jahr). Wann dies fertig ist, soll der aktualisierte Import nochmal stattfinden.

**Comment by asudau** [comment]
Wir haben ja schon einen Filter für Berichtsjahr 2018 also nur die EInträge die für diesen Jahresbericht relevant sind. Den könnten wir ja einfach festsetzen oder optional tatsächlich alles löschen was nicht mehr relevant ist.. Für die Nutzer mach das am Ende keinen Unterschied, die sehen die alten Einträge dann gar nicht mehr..

**Comment by adedden** [comment]
Angeblich fehlen noch viele Promotionsende-Daten und müssen die noch gesucht/gefunden werden. Dies ist eine Aufgabe für ZBW. Wenn die Promotionsdaten gefunden sind, soll die Importdatei hiermit aktualisiert werden und nochmal importiert werden. Es stimmt: das Filter für BJ 2018 wird dann viel mehr Fälle heraus filtern, wir müssen meiner Meinnung nach nichts löschen.

**Comment by asudau** [comment]
die einträge von 11/2017 waren mein Fehler da mussten die 12/2017 rein, das passt jetzt.. den filter aktuelles Bersichtsjahr habe ich jetzt schonmal als Default gesetzt..

**Comment by sonschul** [comment]
Die Daten wurden aber noch nicht neugeladen, oder? 
Zumindest sind immer noch deutlich zu viele Datensätze vorhanden. :-/

**Comment by asudau** [comment]
ja, es wird gerade noch ein neuer export aus his fertig gemacht den ich dann importiere..
