### ISSUE TITLE
Admin Accounts anlegen

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#119]
Für Sonja "sonschul" und Kathrin "kaschnie"

**Comment by sonschul** [comment]
für test- und spätere supportzwecke wären user wie promo-fb01, promo-fb03 etc. sehr hilfreich.  
damit könnte auch unser hiwi nach und nach die einzelnen fachbereiche überprüfen.

**Comment by adedden** [comment]
auch für heike hdalingh

**Comment by sonschul** [comment]
Hat kaschnie auch schon Zugang bekommen?

**Comment by asudau** [comment]
jetzt ja, es fehlte noch die Pluginrolle

**Comment by asudau** [comment]
promo-fb01, promo-fb03 brauchen wir dann ja insbesondere fürs Produktivsystem, die würde ich dann erst da anlegen

**Comment by sonschul** [comment]
Sind schon die Testuser angelegt worden? 
Damit würden wir dann unseren HIWI arbeiten lassen.

**Comment by sonschul** [comment]
siehe #193

**Comment by asudau** [comment]
dopplung zu #193
