### ISSUE TITLE
Datenexport (ef014u1) und (ef014u2)

### ISSUE THREAD

**Issue by sonschul** [asudau/Promovierendenverwaltung#121]
Ende-Datum (ef14) darf nur gefüllt sein, wenn Art der Registrierung (ef12) = "Abbruch" oder "Erfolgreicher Abschluss". 

Im Datenexport wird bei allen laufenden Promotionen 12/2018 als Datum gesetzt.

**Comment by sonschul** [comment]
Das Feld sollte unbedingt leer bleiben, wenn kein Ende der Promotion (Abschluss oder Abbruch) eingetragen ist.

**Comment by asudau** [comment]
was genau muss denn jetzt geändert werden?  
wenn kein Ende der Promotion (Abschluss oder Abbruch) eingetragen ist kann man diese Felder nicht editieren.. muss dann zusätzlich noch sichergestellt werden dass hier nix drin steht?  
'Im Datenexport wird bei allen laufenden Promotionen 12/2018 als Datum gesetzt' -> das passiert ja schon und ist auch richtig so oder?

**Comment by sonschul** [comment]
Beim Datenexport sollen die Felder (ef014u1) und (ef014u2) leer bleiben, wenn kein Ende der Promotion angegeben ist.

**Comment by asudau** [comment]
alles klar, danke!
