### ISSUE TITLE
Abgeschlossene Promotionen aus Datenbasis entfernen

### ISSUE THREAD

**Issue by sonschul** [asudau/Promovierendenverwaltung#122]
Da das Tool "Doktorandenverwaltung" nur der Verwaltung laufender Promotionsverfahren dient, sollten alle abgeschlossenen Promotionsverfahren (Eintrag bei Ende der Promotion zum Teil vor 2017) aus der Datenbasis entfernt werden.

Im nächsten Berichtszyklus sollten dann ebenfalls nach erfolgreicher Abgabe der Statistik alle abgeschlossenen Verfahren entfernt werden.

**Comment by adedden** [comment]
Hallo Sonja, dieses Filter ist schon drin. Aber weil es die Endedaten fehlen, werden die Einträge nicht ausgefiltert. An euch die bitte die Endedaten zu den Promovierenden zu finden. Siehe Ticket #118
