### ISSUE TITLE
Highlighting der nicht ausgefüllte Plichtfelder

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#127]
Die Einschätzung von ZBW ist das die komplett rot gefarbte Zeilen ein wenig demotivierend wirkend für die Mitarbeiter, die die Eingaben einträgen müssen, besonderes wenn man ein neuer Eintrag anlegst.
Wäre es möglich:
- Das Highlighting zu beschränken auf einem Rand um dem Eintragsfeld?
- Das Highlighting in der Maske "New Entry" rauszulassen?

Lass uns dies nach deinem Urlaub eben kurz durchsprechen!

**Comment by asudau** [comment]
vllt ein lightblue? 
![grafik](https://user-images.githubusercontent.com/11834384/47072426-3c61c300-d1f6-11e8-8a45-48b79e9e3342.png)  

kann es glaub ich auch beim new entry ganz rauslassen, aber es soll ja beim ausfüllen helfen somit wär das vllt gar keine so gute idee

**Comment by sonschul** [comment]
Das blau finde ich wesentlich benutzerfreundlicher, allerdings bin ich immer noch dafür in der Eingabemaske "Neuer Eintrag" die Farbe wegzulassen und zwar vor allem aus den folgenden zwei Gründen: 

1. Wenn das Feld einmal bearbeitet wurde und dann geleert wird, erscheint kein Highlighting mehr. (siehe Screenshot: Vorname)
2. Es findet auch keine Validierung statt. (siehe Screenshot: Geburtsdatum)

![grafik](https://user-images.githubusercontent.com/40201793/47145309-b020d000-d2c9-11e8-8e92-0ad5b901e332.png)

**Comment by sonschul** [comment]
Im Prinzip reicht es doch aus, die roten Sternchen als Pflichtfelder zu markieren. 

Bitte zu diesem Thema auch noch den Promovierenden "Testfehler" anschauen, den ich heute Morgen angelegt habe. Dieser Promovierende wurde mit folgenden Hinweis in die DB übernommen, obwohl Daten fehlen und Angaben falsch sind. (Kein Staat hinterlegt, obwohl Auslandshochschule angegeben, Vorname fehlt ganz, kein Geschlecht, und hat dann einen 91% vollständigen Datensatz?!) 

![grafik](https://user-images.githubusercontent.com/40201793/47145710-b2cff500-d2ca-11e8-9824-67759683d9ba.png)

**Comment by sonschul** [comment]
Entweder der Datensatz kann gar nicht angelegt werden, oder wird angelegt, aber fehlerhafte Angaben werden der Benachrichtigung mit ausgewiesen z.B. "Die Änderungen wurden übernommen. Achtung! Vorname fehlt."

**Comment by asudau** [comment]
Hinweis dass noch Angaben fehlen wenn das so ist...

**Comment by asudau** [comment]
Farbe ändern in blau  
keine farbhervorhebung beim anlegen neuer einträge  
Validierung von Geburtsdatum  
Rückmeldung nach dem Speichern über fehlende Einträge

**Comment by asudau** [comment]
[keine Hervorhebungen beim Anlegen neuer Einträge](https://github.com/asudau/Promovierendenverwaltung/commit/7b1a95855cf1cdc21da50b78a84db0aaec913bd8)
