### ISSUE TITLE
Neuladen der Daten/ Abgeschlossene Promotionen/ Ende der Promotion (POS) 

### ISSUE THREAD

**Issue by sonschul** [asudau/Promovierendenverwaltung#132]
Bitte prüfen, ob beim nächsten Neuladen der Daten möglich ist das Ende-Datum der Promotion für abgeschlossene Promotionen aus der Prüfungsverwaltung zu übernehmen. Bei der letzten Statistiklieferung wurden auch nicht alle jemals abgeschlossenen Promotionen mitgeliefert wie sie jetzt (mit über 3.000 Datensätzen) im Modul angezeigt werden. 

Daher folgende zwei Punkte beim Neuladen der Daten beachten: 

1. Vor Dezember 2017 abgeschlossene Promotionen sollten **gar nicht** in das Modul Doktorandenverwaltung übernommen werden, weil diese statisisch nicht relevant sind. 

2. Alle zwischen Dezember 2017 und Dezember 2018 abgeschlossenen Promotionen können auf den Status "erfolgreich abgeschlossenen" gesetzt werden. Idealerweise mit Ende Datum der Promotion aus POS. Falls dies nicht automatisiert möglich ist, könnte dieser Punkt auch von unserem Hiwi übernehmen werden.

**Comment by sonschul** [comment]
Da ca. 2.000 Promovierende zu viel in der aktuellen Datenbasis stehen, können wir die Daten der abgeschlossenen Promotionen auf keinen Fall händisch einpflegen. Im Zweifel bitte noch mal mit Heike kurzschließen, wie man entsprechende Daten aus POS ziehen kann. 

In der Meldung an das Landesamt wurden 1.046 Datensätze abgegeben, die sich entsprechend in der Datenbasis (bereinigter Datenstand) wiederfinden müssten.

**Comment by adedden** [comment]
#118
