### ISSUE TITLE
Testaccount anlegen mit FB-Zurordnung

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#135]
Für ZBW, zum testen

**Comment by asudau** [comment]
PVW_Biologie: testing (FB Biologie/Chemie)  
PVW_Geschichte: testing (FB 1 Kultur- und Sozialwissenschaften)  
PVW_Rechtswissenschaft: testing (FB 10: Rechtswissenschaften)

**Comment by asudau** [comment]
Username: passwort

**Comment by adedden** [comment]
Testen ist noch nicht abgeschlossen

**Comment by asudau** [comment]
hey ihr lieben, die fächerzuordung funktioniert jetzt, (war nur eine zeile im code und betraf fächer mit 2-stelliger statt dreistelliger id)  :-)  
LG!

**Comment by adedden** [comment]
Getestet auf TST, dort funktioniert es richtig.
