### ISSUE TITLE
Endedatum der Promotion - automatisch löschen

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#136]
Wenn Anwender Art der Registrierung, ungleich Abrruch der Promotion oder Erfolgreicher Abschluss der Promotion wählen, dann automatische Ende der Prom Datum (Jarh und Monat löschen

**Comment by asudau** [comment]
krieg ich leider in der oberfläche nicht live hin (zumindest nicht für den Monat, das ist total kompliziert zusammengebaut weil das was der nutzer sieht nicht das eigenltihce select objekt ist..). Beim Speichern werden die Werte allerdings entfernt, das ist kein Problem..

**Comment by asudau** [comment]
wenn diese ticket grad formal noch bei mir liegt brauch ich da ggf. nochmal feedback/austausch um zu entscheiden wie wir an dieser Stelle jetzt weiter verfahren..

**Comment by adedden** [comment]
Mache ich morgenfrüh! War ich noch nicht zu gekommen!

**Comment by adedden** [comment]
> krieg ich leider in der Oberfläche nicht live hin (zumindest nicht für den Monat, das ist total kompliziert zusammengebaut weil das was der nutzer sieht nicht das eigenltihce select objekt ist..). Beim Speichern werden die Werte allerdings entfernt, das ist kein Problem..
Dieses Verhaltet habe ich nochmal getestet/nachgestellt, Monat und Jahr werden in der Tat gelöscht, dann braucht dieses Ticket nicht bearbeitet werden und schließe ich es.
