### ISSUE TITLE
Promotionsfach

### ISSUE THREAD

**Issue by asudau** [asudau/Promovierendenverwaltung#137]
Nur eben als Hinweis (es wird ja nochmal einen neuen Export geben, vllt ist es dann erledigt):  
Ich habe ja kürzlich die Liste der Promotionsfächer auf wunsch aktualisiert, es gibt jetzt noch 37 einträge.  
   
Im aktuellen Datenbestand gibt es allerdings 59 verschiedene IDs die für die Angabe des Promotionsfachs verwendet werden. Wenn es hier also noch zu Problemen kommt, liegt das daran. Sollte das durch einen aktualisierten Export nicht behoben werden können müsste man das ggf. nochmal ansehen..

**Comment by asudau** [comment]
hat sich geklärt, dort wo keine aufschlüsselung des promotionsfachs möglich ist, ist die angabe falsch und der eintrag muss ohnehin manuell bearbeitet werden

**Comment by sonschul** [comment]
@hdalingh hat mich noch mal darauf hingewiesen, dass die Liste der Promotionsfächer nicht ganz korrekt ist z.B. sollte es "Adv.Materials /Asy" nicht geben. Die Liste hatte ich bereitgestellt, oder?

**Comment by asudau** [comment]
huhu, ja genau die liste hatte ich von dir übernommen
