### ISSUE TITLE
hzb_land raus

### ISSUE THREAD

**Issue by asudau** [asudau/Promovierendenverwaltung#138]
Derzeit ist das in der Datenbank noch drin (Spalte 39) ich verstehe das aber so, dass wir das nicht separat erfassen müssen/wollen weil es sich aus hzb_kreis ergibt? Die letzten beiden zahlen oder so? Dann würde man es ja sinnvollerweise eher berechnen in dem Moment in dem man es braucht.

Dann müsste es aus dem Formular raus, aus der Datenbankstruktur raus und ich würde stattdessen die dynamische Berechnung einbauen?

**Comment by asudau** [comment]
die ersten beiden zahlen in astat-wert von hzb_kreis ist gleich hzb_land

**Comment by sonschul** [comment]
@asudau Nimmst du das dann auch aus der Maske raus?

**Comment by asudau** [comment]
für den export muss noch ein interner getter geschrieben werden

**Comment by asudau** [comment]
s.o.
