### ISSUE TITLE
Import der Daten - Datenbasis (Auslandshochschule)

### ISSUE THREAD

**Issue by sonschul** [asudau/Promovierendenverwaltung#142]
Bei ausländischen Studierenden werden die Felder „Hochschule der Abschlussprüfung“ und „Hochschule der Ersteinschreibung“ nicht mehr korrekt gefüllt, wenn ein Staat im Ausland angegeben wurde. 
Es müsste in beiden Feldern die Auswahl „Auslandshochschule“ ausgewählt sein. 
Bitte für alle Promovierende aus dem Ausland die Einträge „Auslandshochschule“ nachladen.

**Comment by kaschnie** [comment]
![beispiel_auslandischehochschule](https://user-images.githubusercontent.com/44695704/47905635-dd53ad80-de87-11e8-80dd-c23483e55fbf.jpg)

**Comment by asudau** [comment]
das war teil des aktualisierten imports oder?

**Comment by sonschul** [comment]
Ich glaube nicht, dass der Fehler durch den aktualisierten Import behoben wurde: 
Zumindest ist beim Großteil der ausländischen Promovierende (Bsp. Biologie) nun gar nichts mehr bei den Abschluss-Daten vorhanden.
z.B. 966653 , 966587 , 967172 ...

**Comment by asudau** [comment]
ich würde das mal direkt über die datenbank beheben.. es gth doch um die aktuell vorhandenen Einträge oder?

**Comment by asudau** [comment]
das sähe dann so aus, ginge ganz fix ich warte aber erst noch auf zustimmung    
UPDATE `doktorandenverwaltung` SET hochschule_erst = 2 WHERE `staat_hochschule_erst` NOT IN ('48','NULL','')  
UPDATE `doktorandenverwaltung` SET hochschule_abschlusspruefung = 2 WHERE `staat_abschluss` NOT IN ('48','NULL','')

**Comment by sonschul** [comment]
2 steht für Auslandshochschule 
und wofür steht 48 ?

**Comment by asudau** [comment]
48 ist deutschland

**Comment by sonschul** [comment]
Dann sieht das meiner Meinung nach richtig aus!

**Comment by asudau** [comment]
ich würde das noch beschränken uaf einträge die keine angabe bei hochschule_abschlusspruefung oder hochschule_erst = 2 haben. Leider gibt es unplausible einträge:  
ich habe z. B einen gefunden der als hochschule darmstadt hat und als land china

**Comment by sonschul** [comment]
Diese Angaben werden wohl nur von den Fachbereichen korrigiert werden können.  
Es sollte also pro Fachbereich eine Liste der zu korrigierenden Fälle geben, weil wir vom Landesamt auch auf einige Inkonsistenzen hingewiesen wurden... (Abitur mit 8 Jahren etc... )

**Comment by adedden** [comment]
> UPDATE `doktorandenverwaltung` SET hochschule_erst = 2 WHERE `staat_hochschule_erst` NOT IN ('48','NULL','')
> UPDATE `doktorandenverwaltung` SET hochschule_abschlusspruefung = 2 WHERE `staat_abschluss` NOT IN ('48','NULL','')

Hallo Annelene, du kannst diese Felder so bereinigen, aber nur wenn die Felder (hochschule_erst und hochschule_abschlusspruefung) leer sind.

Die inkonsistente Angaben müssen von den Fachbereichen bereinigt werden, stimme Sonja zu.

**Comment by asudau** [comment]
UPDATE doktorandenverwaltung SET hochschule_erst = 2 WHERE staat_hochschule_erst NOT IN ('48','NULL','') AND hochschule_erst NOT IN ('NULL','')
