### ISSUE TITLE
Import der Daten - Datenbasis (Prüfungsdaten)

### ISSUE THREAD

**Issue by sonschul** [asudau/Promovierendenverwaltung#143]
Bei AbsolventInnen der Universität Osnabrück müsste der Abschnitt "Daten zur Promotion berechtigender Abschluss" vollständig gefüllt sein. In der Datenbasis werden aber z.T. nur unvollständige Daten angezeigt z.B. nur die Prüfungsnote statt der vollständige Abschluss. 
Diese Daten sollten idealerweise aus POS vollständig nachgeladen werden.

**Comment by adedden** [comment]
Dies wird durch Heike am 1.11.2018 durchgeführt, sie liefert die Daten am 2.11 an Annelene.
