### ISSUE TITLE
Leerzeilen entfernen 

### ISSUE THREAD

**Issue by sonschul** [asudau/Promovierendenverwaltung#144]
Bei Promovierenden mit MTKNR, aber ohne Angabe des Promotionsfachs sollten fehlende Daten nachgetragen werden.

**Comment by asudau** [comment]
ist bei diesem Ticket eigentlich schon klar wer das macht/machen kann?

**Comment by sonschul** [comment]
Kann glaub ich schon geschlossen werden, weil alle Leerzeilen entfernt wurden.
