### ISSUE TITLE
Teilnahme an einem strukturierenden Promotionsprogramm 

### ISSUE THREAD

**Issue by sonschul** [asudau/Promovierendenverwaltung#145]
Bei Fächern/Fachbereichen, die eindeutig keine Teilnahme an einem Graduiertenkolleg anbieten, sollte für die Promovierenden "Kein strukturiertes Promotionsprogramm" hinterlegt werden. 
z.B. Wirtschaftswissenschaften, Rechtswissenschaften, Physik, Textiles Gestalten...

**Comment by adedden** [comment]
Diese Anforderung wird eingestuft als eine zusätzliche Service-Erweiterung für Meilenstein "Phase 2"

**Comment by adedden** [comment]
Morgen! @sonschul kannst du diese "inhaltliche" Punkte, "so fülle ich einen Feld richtig aus", sammeln? Es scheint mir sinnvoll dass diese Doku durch ZBW geschrieben wird und die reine technische, "wie ist das Tool zu bedienen-Doku", durch uns.

**Comment by adedden** [comment]
@asudau das Anpassen des Feldes "StrukPromotionsprogramm_Standardtext", wenn es leer ist, gleich "Kein strukturiertes Promotionsprogram" setzen

**Comment by sonschul** [comment]
Ist das noch offen?

**Comment by adedden** [comment]
Entschuldigung, ich hatte mit dem falschen Meilenstein versehen, dass muss noch umgesetzt werden.

**Comment by asudau** [comment]
also für mich sieht das inwzischen soweit alles richtig aus. Der Text passt und in der DB steht dort bei allen Einträgen 0 - also kein Programm..
