### ISSUE TITLE
Abbruch der Promotion

### ISSUE THREAD

**Issue by sonschul** [asudau/Promovierendenverwaltung#146]
Bei allen Promovierenden, die im letzten Datenstand (2017) mit dem Status "Abbruch der Promotion" gemeldet wurden, sollte bei unbekannten Abbruch-Datum als Promotions-Ende: 12 / 2017 gesetzt werden. 

Hier noch mal der Auszug aus dem Schlüsselverzeichnis: "Wird in EF12 der Abbruch der Promotion gemeldet, so ist hier der Termin des Abbruchs anzugeben. Ist der Termin nicht bekannt, so ist der
Dezember des jeweiligen Berichtsjahres zu setzen."

![grafik](https://user-images.githubusercontent.com/40201793/47864528-1ba28b80-ddfa-11e8-8554-fd035671c5cd.png)

**Comment by adedden** [comment]
@sonschul : wenn wir das machen, werden alle diese Datensätze in der Meldung für 2018 wieder mitgenommen werden (nämlich alle Abschlüsse zwischen 1.12.2017 und 1.12.2018 werden gemeldet). Ist dies so erwünscht?

**Comment by sonschul** [comment]
Das ist nicht gewünscht, dass bereits im letzten Jahr als abgebrochenen Promotion gemeldete Promovierende wieder in der Meldung auftauchen. Die müssen ganz raus und nicht ewig weiter auftauchen. Bei den Promovierenden soll auch gar nichts mehr nachgetragen oder vervollständigt werden von den Fachbereichen. 

Nein, bei erfolgreichem Abschluss muss das tatsächliche Ende der Promotion (lt. Prüfungsstatistik) eingetragen werden.

**Comment by asudau** [comment]
"Wird in EF12 der Abbruch der Promotion gemeldet, so ist hier der Termin des Abbruchs anzugeben. Ist der Termin nicht bekannt, so ist der Dezember des jeweiligen Berichtsjahres zu setzen." das ist ja irgendiwe verrückt. 
Effektiv heißt das dann für die Meldung:  
Wenn irgendwann 2017 abgebrochen wurde aber zum Berichtszeitpunkt für 2017 keiner reingeschrieben hat wann genau, schreibt man 12/2017 rein und meldet das im Bericht für das Jahr 2017.    
Wenn offiziell im Dezember 2017 abgebrochen wurde schreibt man das auch rein und meldet das im Bericht für 2018.  
Oder versteh ich das ganz falsch?  Es wird dann nämlich tatsächlich geradezu unmöglich zu wissen welche Einträge mit in den Bericht für 2018 fließen sollen und welche nicht, denn die unterscheiden sich ja quasi dann nur darin wann die Information vorlag bzw. ob sie im Bericht für 2017 schon aufgetaucht waren. Und das kriegen wir rückwirkend nur schwer raus oder??

**Comment by adedden** [comment]
Diese Filterung gilt für die zwei Stati: 5 und 6. 
"Die Meldung des Abschlusses sowie des Abbruchs der Promotion dient
dazu, den Bestand der Promovierenden in der Promovierendenstatistik
aktuell zu halten."

@sonschul wir haben dies besprochen und stellen 2 neue Tickets: einer für die Filterung des Exportes und einer für das exportierte Datum

**Comment by adedden** [comment]
das Exportierte Datum: #152

**Comment by adedden** [comment]
Nur für das Export, wir wollen in dem Tool nicht automatisch Daten ausfüllen, weil wir hiermit die Chance für Anwender wegnehmen, die richtige Daten nachpflegen zu können. Die richtige Anzeige für Anwender und der richtige Export sind gewährleistet (sollen natürlich zur Sicherheit getestet werden)
