### ISSUE TITLE
Datenfeld - wurde berichtet

### ISSUE THREAD

**Issue by asudau** [asudau/Promovierendenverwaltung#151]
um Einträge welche abgebrochen wurden und deren Ende Datum unbekannt ist (oder auf Dezember des Berichtsjahres gesetzt werden) nicht im Folgejahr erneut zu melden wird zukünftig vermerkt, wenn ein Eintrag als abgeschlossen oder beendet in einen Bericht eingeflossen ist

**Comment by adedden** [comment]
Ich würde dies noch erweitern: an alle Anträge (unabhängig von Status) soll vermerkt werden per Berichtsjarh: vermeldet worden in Berichtsjahr X (damit man später auf diesen Informationen zurückgreifen kann)

**Comment by sonschul** [comment]
Wir werden die Daten der Meldung für Berichtszwecke in unserem MIS aufbereiten. Dort werden alle Datensätze mit dem jeweiligen Datum der Meldung historisiert, um Zeitreihen für die Promovierenden abzumelden. Es sollte also nicht zu viel Zeit in diese Aufgabe gesteckt werden, weil das Tool primär für die Erfassung und die Statistik gedacht ist.

**Comment by adedden** [comment]
Hallo Sonja, du hast Recht dass das Tool nur für die Erfassung der Statistik dient und hierfür temporär HISinOne ersetzt. Weil wir später die Daten zurückspielen müssen in HISinOne und wir die Qualität zurückspielen gewährleisten können, müssen wir die Daten speichern. Ziel ist dass für die Anwender nur das aktuellen Berichtsjahr angezeigt wird.

**Comment by sonschul** [comment]
Ist das Ticket noch offen? 
Bitte überpüfen, ob die Daten für alle abgebrochenen Promovierenden korrigert wurde.
Bsp: 934838

**Comment by adedden** [comment]
Dieses Ticket ist noch nicht umgesetzt worden. Annelene meldet sich zurück, wenn sie so weit ist.

**Comment by adedden** [comment]
Umgeschrieben in mehrere Tickets: #172, #173 , #174
