### ISSUE TITLE
Exportfilter - Abbruch/Abschluss vorherigen Berichtsjahr

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#153]
Für Berichtsjahr X soll die Fälle herausgefiltert werden, die in Berichtsjahr X-1 meldet wurden und wenn ef12 Art der Registrierung als Promovierender gleich 5 = Abschluss der Promotion (bestanden oder endgültig nicht bestanden) oder 6 = Abbruch der Promotion ist UND 14u1 und/oder 14u2 sind leer.

**Comment by adedden** [comment]
Heike bereinigt Fälle

**Comment by asudau** [comment]
der filter an sich ist schon drin, ggf muss jetzt nur sichergestellt werden, dass #173 korrekt befüllt ist
