### ISSUE TITLE
Doppelte Auswahl von Fach und Abschluss bei der zur Promotion berechtigten Abschlussprüfung

### ISSUE THREAD

**Issue by hdalingh** [asudau/Promovierendenverwaltung#155]
Hallo zusammen,

bei der Auswahl des Abschlusses und des Faches bei "Daten zur Promotion berechtigten Abschlussprüfung" werden bestimmte Abschlüsse und Fächer doppelt angeboten z.B. Abschluss 08 einmal als "Erste Prüfung (jur.)" und einmal als "Staatsexamen". Der Grund dafür ist, dass es bei diesen Abschlüssen sowohl einen internen Schlüssel von uns gibt, als auch einen Schlüssel als externer Abschluss. Hier müssten wir uns auf eine Variante einigen, also ob die Bearbeiter über unsere Benennung (hier "Erste Prüfung (jur.)" ) auswählen sollen oder über den generelllen externen Ausdruck "Staatsexamen".

Gruß
Heike

**Comment by hdalingh** [comment]
Hallo Sonja,
da müsste man dann vielleicht einfach die Namensfelder der Schlüsseltabelle, die Annelene verwendet, entsprechend umgestalten. In den produktiven HISinOne-Schlüsseltabellen würde ich diesbezüglich keine Anpassung vornehmen wollen.

**Comment by asudau** [comment]
hmm prinzipiell wäre das möglich aber aus his gibt es sowohl promivierende mit der abschluss lid 100275 = Staatsexamen als auch solche mit 100103 = Erste Prüfung.  
Wenn wir die auswählbaren fächer wie oben beschrieben einschränken/zusammenführen könnten wir bei vorhandenen inträgen nicht mehr beide abschlüsse aufschlüsseln

**Comment by sonschul** [comment]
Könnt ihr mir die dazugehörigen MTKNR schicken, damit ich mir diese Fälle mal anschauen kann?

**Comment by asudau** [comment]
mtknr: 662707 fach lid: 100103  
mtknr: 900160 fach lid: 100275  
mtknr: 907066 fach lid: 100275  
mtknr: 909494 fach lid: 1001

**Comment by adedden** [comment]
Wird jetzt gelöst durch zusatext "Erste Prüfung (jur.) (Universitat Osnabrück)" und Staatsexamen (extern)

**Comment by adedden** [comment]
Weitere Dupletten suchen

**Comment by asudau** [comment]
ok also der krasseste fall ist hier astat_bund = 40: 
![grafik](https://user-images.githubusercontent.com/11834384/48201987-f8c92780-e363-11e8-9194-fd18595b8d9a.png)

und was machen wir damit?

**Comment by sonschul** [comment]
Im Prinzip kann der Abschluss unter Lehramt an Grundschule zusammengefasst werden. 
Wenn ich das richtig sehe, sind es die alten Lehramtsabschlüsse, oder? 
Eventuell wäre ein Hinweis wie (kein BA/MA) ganz gut.

**Comment by asudau** [comment]
das hier bleibt in der lösung schwierig, evtl müssen wir daarüber sprechen. Für jura hatten wir ja überlegt den hinweis extern dahinter zu schreiben aber funktioniert das auch bei 7 äuiqvalenten werten? Ein reines zusammenführen geht wie schon gesagt nicht, weil man dann auch die einzelnen promovierenden-datensätze ändern/verfälschen müsste damit diese noch aufgeschlüsselt werden könnten.

**Comment by adedden** [comment]
Dieses Problem soll durch die Synchronisierung mit HIO gelöst werden
