### ISSUE TITLE
Neues Pflichtfeld - E-Mailadresse

### ISSUE THREAD

**Issue by sonschul** [asudau/Promovierendenverwaltung#156]
Es ist für das Produktivsystem noch zwingend ein Feld für die E-Mailadresse erforderlich. 
Bei Rückfragen dazu bitte Frau Brüggemann kontaktieren!

**Comment by adedden** [comment]
Hier brauchen wir von ZBW eine Liste der Emailadressen der Promovierenden

**Comment by sonschul** [comment]
Der Großteil der E-Mailadresse kann (laut Heike) aus den Imma-Daten übernommen werden, den Rest können wir eventuell aus den Excel-Listen nachliefern.

**Comment by asudau** [comment]
hier brauche ich noch eine tabelle doer csv mit hisperson id (oder ähnliches für das mapping) und emailadresse

**Comment by asudau** [comment]
erledigt, die vorhandenen mailadressen sind jetzt fester bestandteil der daten, falls noch weitere kommen wäre es kein problem die nachzupflegen..
