### ISSUE TITLE
Text im InfoButton "Ende der Promotion - Jahr" unvollständig

### ISSUE THREAD

**Issue by sonschul** [asudau/Promovierendenverwaltung#157]
Bitte Textfeld des InfoButtons "Ende der Promotion - Jahr" überprüfen. Hier wurde Text abgeschnitten.

**Comment by asudau** [comment]
sollte jetzt passen (allgemein fehlten nach dem umzug ein paar hilfetexte) wenn der fehler noch besteht ist das möglicherweise auch ein browser-ding, dann bitte bescheid geben

**Comment by adedden** [comment]
Problem scheint behoben. Habe keine Probleme in Chrome, Explorer oder in Firefox. Ich schließe darum das Ticket.

**Comment by kaschnie** [comment]
Bei mir klappt es mit der aktuellsten Internet Explorer-Version leider immer noch nicht. Wir können es für diesen Ausnahmefall doch einfach in den FAQ mit aufnehmen?!
