### ISSUE TITLE
Text InfoButton "Teilnahme an einem strukturierenden Promotionsprogramm: "

### ISSUE THREAD

**Issue by sonschul** [asudau/Promovierendenverwaltung#158]
Bitte folgenden Text als InfoButton hinterlegen: "Zu den strukturierenden Promotionsprogramm zählen lediglich die Graduiertenkollegs. (keine Promotionsstudiengänge)"

Um eventuelle Rückfragen zu vermeiden!

**Comment by asudau** [comment]
ist drin
