### ISSUE TITLE
Abschlussnote Staatsexamen Jura

### ISSUE THREAD

**Issue by sonschul** [asudau/Promovierendenverwaltung#159]
Bitte anhand des Datensatzes von 980999 überprüfen, ob die Abschlussnote des vorherigen Studiums immer korrekt übernommen wurde. Eventuell war die Notenskala nicht kompatibel? (vollbefriedigend)

**Comment by adedden** [comment]
Noch aktuell?

**Comment by adedden** [comment]
Wegen fehlender Rückmeldung geschlossen
