### ISSUE TITLE
Validität der Daten - Immatrikulationsstatus / MTKNR 

### ISSUE THREAD

**Issue by sonschul** [asudau/Promovierendenverwaltung#160]
Leider ist heute Morgen aufgefallen, dass beim Laden der Matrikelnummern und des Immatrikulationsstatus (ja/nein) nicht beachtet wurde, ob der Immatrikulationsstatus überhaupt noch aktuell ist. 
Bsp: 953746 (Promovierende war zuletzt 20152 immatrikuliert und steht in der Promovierendenverwaltung als Immatrikuliert - ja mit Matrikelnummer)

**Comment by adedden** [comment]
@Heike kannst du eine Liste ziehen aus HIO mit aktuell Eingeschriebenen?

**Comment by hdalingh** [comment]
Die Frage ist, wie soll man generell bestimmte Fallkonstellation behandeln. Zum Beispiel:
Fall 1: Person ist bereits beim FB bekannt und drei Semester am promovieren ohne eingeschrieben zu sein. Dann überlegt die Person sich doch noch einzuschreiben bzw. schreibt sich ein, weil er seine Promotion abschließen will.
Fall 2: Person ist eingeschrieben als Promotionsstudent über mehrere Semester und beschließt dann, weil er so keinen Nutzen mehr von der Einschreibung hat, sich zu exmatrikulieren. Seine Promotion macht er jedoch trotzdem noch weiter.
Gemäß diesen Fällen müsste man immer schauen, ist die Person aktuell noch eingeschrieben oder nicht. Nur weil bei der Person eine Matrikelnummer steht, bedeutet es nicht, dass sie als Promotionsstudierender eingeschrieben ist. Die Matrikelnummer der Person kann auch von seinem vorherigen Studium stammen.

**Comment by adedden** [comment]
Umsetzung soll sein wie folgt: ImmaNr wird nicht gelöscht, ist ein Suchmerkmal für die Mitarbeiter.
Immatrikulationsstatus muss manuell eingepflegt werden, bis die automatische Aktualisierung funktioniert (#66)

**Comment by adedden** [comment]
Die Immastatus des Anfangsbestand muss überschrieben werden mit dem Stand van dem Statistikstand 2017

**Comment by adedden** [comment]
Heike geht die Fälle manuell durch
