### ISSUE TITLE
FAQ / Dokumentation - Browserfunktionalität (Suchfunktion) 

### ISSUE THREAD

**Issue by sonschul** [asudau/Promovierendenverwaltung#161]
Bitte Browserkompatibilität in der Dokumentation und FAQ - Liste erklären. 
Die Sortierfunktion funktioniert im Internet Explorer nicht.

**Comment by adedden** [comment]
Hallo Zusammen, bevor wir in der Doku mitaufnehmen, dass der Sortierung in Explorer nicht funktioniert, hätte ich lieber dass es einfach in unterschiedlichen Browser funktioniert. @asudau wie schwierig ist es, dieses Sortierungsproblem zu beheben? Wenn es sehr zeitaufwendig wird, dann müssen wir es so lassen, wie es jetzt ist und nehme ich es in der Doku mit auf.

**Comment by asudau** [comment]
das ist vermutlich ein generelles studip problem, das muss ich erstmal reproduzieren und dann kann ich da ggf. was zu sagen

**Comment by adedden** [comment]
Welche Browser sind Stud.IP kompatibel? Dann nehme ich das in der Doku mit auf.

**Comment by kaschnie** [comment]
Kompatibel sind Chrome und Firefox.. Ich würde später nochmal Microsoft Edge und Opera testen. Jetzt gerade erhalte ich gerade eine Fehlermeldung, wenn ich mich anmelden möchte (Fehlermeldung: •SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hzb_land' in 'field list')

**Comment by asudau** [comment]
betrifft das das testsystem oder das produkticsystem? beim testsystem würde ich wissen woran das liegt..  
Iihr habt inzwischen übrigens alle Zugriff aus Produktivsystem

**Comment by asudau** [comment]
der fehler ist behoben - das mit dem sortieren nimmt sich gerade ein studip entwickler vor. Ich gehe derzeit davon aus dass das diese woche noch behoben werden kann..

**Comment by asudau** [comment]
das sortierproblem ist von einem entwickler gefixt, elmar muss das aber noch in unser studip system übernehmen, denke das passier heute oder montag

**Comment by asudau** [comment]
ist behoben
