### ISSUE TITLE
Testen der Statistikexport

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#162]
Es soll getestet werden durch ZBW ob der Umschlüsselung in der Statistikexport so stimmt. Dies kann bereits angefangen werden, bevor das Import vervollständig worden ist. Damit keine Zeit verloren geht.

**Comment by asudau** [comment]
der export geht jetzt auch wieder (zwischenzeitlich gab es da probleme)

**Comment by sonschul** [comment]
Wäre es möglich für Testzwecke im neuen System auch unseren HIWI freizuschalten?

**Comment by kaschnie** [comment]
Könnte ich auch eine Berechtigung für das Produktivsystem bekommen? :-)

**Comment by asudau** [comment]
Oh nein, hab ich dich etwa vergessen!? Ich kümmer mich drum!

Am 7. November 2018 08:11:13 MEZ schrieb kaschnie <notifications@github.com>:
>Könnte ich auch eine Berechtigung für das Produktivsystem bekommen? :-)
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/asudau/Promovierendenverwaltung/issues/162#issuecomment-436526286

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by asudau** [comment]
Hmm hab Grad Mal im system nachgeschaut du bist eigentlich korrekt eingetragen..

Am 7. November 2018 08:11:13 MEZ schrieb kaschnie <notifications@github.com>:
>Könnte ich auch eine Berechtigung für das Produktivsystem bekommen? :-)
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/asudau/Promovierendenverwaltung/issues/162#issuecomment-436526286

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by sonschul** [comment]
Im Statistik Export werden die ersten 5 Spalten mit einer 1 gefüllt. 

Die Werte sollte exakt den Vorgaben des Schlüsselverzeichnis entsprechen: 
1.) sollte die Länge der Spalten immer gleich sein z.B. Spalte ef001 immer 2 Zeichen lang sein, also 03 statt 3, genauso die Spalte ef003 sollte 4 Zeichen lang sein, also 0530 statt 530 usw. Die Anzahl der Zeichen lassen sich aus der Datensatzbeschreibung entnehmen. 
2.)  Die Spaltenbezeichnung bitte ebenfalls aus der Datensatzbeschreibung entnehmen EF3 statt EF003. 
Die Datei wird über ein Online-Portal eingelesen und sonst als fehlerhaft zurückgewiesen. 
3.) EF9 sollte kein NULL enthalten.
4.) EF11 Bitte kontrollieren, ob überall die korrekten ASTAT Werte übernommen werden. Für das Promotionsfach 767 sollte 0281 in der Statistikmeldung geliefert werden. (so stehts zumindest in der Studierendenverwaltung)
5.) Korrektes Abschlussdatum bei erfolgreich bestandenden Promotionsprüfungen (nicht immer 12-2018).
6.) Neu- und Erstregistrierte können nicht vor 12/2017 angefangen haben. (EF 12 i.V.m. EF13U1 und EF13U2)
7.) Aktive Fortsetzung können nicht nach 12/2017 begonnen haben. (EF 12 i.V.m. EF13U1 und EF13U2)

**Comment by adedden** [comment]
Neuer Meilenstein "Statistikexport" angelegt, Tickets übertragen
