### ISSUE TITLE
Astat Studiengangsfach und Promotionsfach

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#168]
In der Statistik müssen 3 Stellen ausgegeben werden, Astat mit 2 Stellen müssen mit einem 0 an anfangen ergänzt werden

**Comment by asudau** [comment]
UPDATE `doktorandenverwaltung_field_values` set astat_bund=concat('00',trim(astat_bund))
WHERE length(trim(astat_bund))=1 AND `field_id` LIKE 'promotionsfach'
