### ISSUE TITLE
"wurde berichtet Berichtsjahr Y" automatisch anlegen

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#174]
Hierzu noch Konzept in der Projektgruppe besprechen: wie technisch umzusetzen.

Ziel: es soll für einen/e Administrator/in möglich sein das definitive Berichtsjahr Y festzustellen.
Dies hat als Auswirkung dass es in der Datenbank ein Feld angelegt wird "wurde berichtet in Berichtsjahr Y" was für alle Datensätze für das betreffende Berichtjahr auf TRUE gesetzt wird.

**Comment by asudau** [comment]
hmm bei der umsetzung muste ich schon wieder umdenken.. Was wir ja eigenltich wissen wollen ist, in welchem Jahr ein Eintrag als abgeschlossen oder beendet berichtet wurde. Ab da fliegt er dann raus. Also habe ich das umbenannt in 'Als abgeschlossen oder abgebrochen berichtet berichtet (Jahr)'

**Comment by asudau** [comment]
für einträge welche im Bericht 2017 als abgeschlossen oder abgebrochen gemeldet wurden kann hier nun hier 2017 eingegeben werden. Den Filter für das aktuelle Berichtsjahr passe ich noch an. Das Feld selbst ist derzeit noch für jeden Nutzer sichtbar solla ber zukünftig unsichtbar werden un bei berichtserstellung per knopfdruck gesetzt werden (vgl #173)
