### ISSUE TITLE
Art der Registrierung (EF12) - Bezeichnung 4 = Beurlaubung / Unterbrechung

### ISSUE THREAD

**Issue by sonschul** [asudau/Promovierendenverwaltung#176]
Bezeichnung der Registrierungsmöglichkeiten bitte der Datzensatzbeschreibung entnehmen: 
1 = Erstregistrierung
2 = Neuregistrierung
3 = aktive Fortsetzung
4 = Beurlaubung / Unterbrechung
5 = Abschluss der Promotion (bestanden oder endgültig nicht bestanden)
6 = Abbruch der Promotion 
noch nicht begonnen (kann so stehen bleiben)

**Comment by asudau** [comment]
erledigt
