### ISSUE TITLE
Zeichenanzahl anpassen

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#181]
ef001 immer 2 Zeichen lang sein, also 03 statt 3, genauso die Spalte ef003 sollte 4 Zeichen lang sein, also 0530 statt 530 usw. Die Anzahl der Zeichen lassen sich aus der Datensatzbeschreibung entnehmen und stehen auch in dem Datenmodel (zur Sicherheit alle mal durchgehen)

**Comment by asudau** [comment]
passt noch nicht für  
EF04  
EF27  
EF06U1 fehlt derzeit im Export

**Comment by asudau** [comment]
die anderen stimmen, zumindest im erzeuge csv bei der anzeige in excel muss man dann ggf vorher festlegen dass es alles textfelder sind (den trick hat heike mir gezeigt ;-)  )
![grafik](https://user-images.githubusercontent.com/11834384/48951222-070b6c00-ef3e-11e8-9b55-8bb733119567.png)

**Comment by kaschnie** [comment]
Wenn ich mir die CSV-Datei ausgeben lasse (Statistikexport), wird leider für alle Spalten nicht die korrekte Zeichenanzahl angezeigt. Meinst du, dass man nun im Anschluss die Excel-Datei händisch angepassen müsste, um die richtige Anzahl Zeichen zu bekommen?

**Comment by asudau** [comment]
magst du mir die entsprechende .csv date mal schicken? und vllt noch dazu eine spalte bei der die anzahl nicht passt?

**Comment by asudau** [comment]
also bei mir sieht das so aus, das ist aber richtig oder?
![grafik](https://user-images.githubusercontent.com/11834384/49070301-9ad58480-f22b-11e8-8f75-c241a7052963.png)

**Comment by kaschnie** [comment]
Wird wohl an meinen Excel-Einstellungen liegen, dass mir das falsch ausgegeben wird. Wenn ich die Datei z. B. mit Word Pad öffne wird mir dort die passende Zeichenanzahl angezeigt.

**Comment by adedden** [comment]
das ist ein Excel Problem, Excel schneidet automatisch alle vorangestellten Nullen entfernt, man muss es wirklich in einer Textbearbeitungsanwendung öffnen
