### ISSUE TITLE
Spaltenbezeichnungen anpassen - Immer "EF+NR"

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#182]
Die Spaltenbezeichnung bitte ebenfalls aus der Datensatzbeschreibung entnehmen EF3 statt EF003.
Die Datei wird über ein Online-Portal eingelesen und sonst als fehlerhaft zurückgewiesen.

Muster ist: EFXX

**Comment by asudau** [comment]
und was ist mit denen die bisher so heißen: ef006u2?
