### ISSUE TITLE
EF9 - Inhalt?

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#183]
Anmerkung von Sonja: EF9 sollte kein NULL enthalten

Frage an Sonja: was soll das Feld dann enthalten? Heike meint dass es letztes Jahr leer geliefert wurde.

**Comment by sonschul** [comment]
Ja, genau. Das muss Leerzeichen, aber nicht den Text "NULL" enthalten. ;-)

**Comment by asudau** [comment]
=> #186
