### ISSUE TITLE
EF16 darf kein NULL enthalten

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#186]
@sonschul: Wenn gleich NULL, dann umändern in 0?

**Comment by sonschul** [comment]
Ich glaub wenn NULL dort steht, dann fehlte die Angabe, also muss das Feld leer bleiben.

**Comment by asudau** [comment]
das betrifft noch einige weitere felder, ist aber technisch gesehen nur eine stelle im code, da brauche ich dann keine weiteren tickets..
