### ISSUE TITLE
Statistikexport erweitern mit Merkmale für die Fehlerbereinigung

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#190]
In der Statistikexport, die zusätzliche Spalten mitausgeben (damit die Zeilen identifiziert und bereinigt werden können):

- Fachbereich
- Nachname
- Vorname
- Geb.Datum
- Matrikelnummer

**Comment by asudau** [comment]
ist jetzt drin, allerdings haben wir tatsächlich für ein promotionsfach (astst = 767) keine entsprechung im studip system.  
dazugehört laut promotionsfachtabelle die fach ID 981 und es handelt sich um das Fach Advanced Materials.  
In der Studip Datenbank gibt es aber nur 
982 Advanced Materials / Biologie  
983 Advanced Materials / Chemie  
986 Advanced Materials / Physik
