### ISSUE TITLE
Funktionsaccounts für Echtsystem

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#193]
Pro Fachbereich soll es ein Funktions-/Testaccount geben, womit die HiWi in ZBW Daten anpassen/nachpflegen kann.

**Comment by asudau** [comment]
gibts dazu eigentlcih schon kennungen die ich freischalten soll? Wenn ja welche, wenn nein wie soll ich die nennen..

**Comment by sonschul** [comment]
Die Frage kann ich dir leider nicht beantworten. Es gibt dauz allerdings noch ein ähnliches Ticket...

**Comment by asudau** [comment]
ok, ich dachte ihr hättet für andere zwecke vlllt bereits kennungen für eure HIWIS aber wenn du davon nix weist würde ich sagen es gibt wohl noch keine..

**Comment by sonschul** [comment]
Oh nein, für die Hiwis nutzen wir keine speziellen Kennungen.

**Comment by adedden** [comment]
Gerne Kennung am 10. Dez freischalten, Liste der Kennungen erfolgt noch

**Comment by adedden** [comment]
Hallo, was ist jetzt hier der Stand? Es soll pro Fachbereich ein Funktionsaccount geben, die die Hiwis von ZBW benutzen können fürs Bearbeiten der Daten.

**Comment by adedden** [comment]
Diese Account sollen sofort freigeschaltet werden

**Comment by kaschnie** [comment]
ja, wir bräuchten wir schon.
