### ISSUE TITLE
Umbenennen erfolgreicher Abschluss

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#196]
Der Eintrag "erfolgreicher Abschluss" in EF12 (Art der Registrierung) ist nicht richtig und soll umbenannt werden nach:
"Abschluss der Promotion (bestanden oder endgültig nicht bestanden)"

**Comment by kaschnie** [comment]
Im Produktivsystem ist die Bezeichnung bereits korrekt hinterlegt

**Comment by adedden** [comment]
Wird mit der Synchronisierung von HIO behoben werden
