### ISSUE TITLE
Namen für Export automatisch generieren (ef007)

### ISSUE THREAD

**Issue by asudau** [asudau/Promovierendenverwaltung#21]
Die ersten 4 Zeichen des Vornamens?  
Müssen die eindeutig sein (scheinbar nicht)

**Comment by adedden** [comment]
Funktioniert diese Umschlüsselung bereits? Beim Testen schein es nicht automatisch generiert zu werden.

**Comment by asudau** [comment]
was ist wenn der vorname kürzer ist als 3 buchstaben? wird der nachname dann dazugenommen?

**Comment by asudau** [comment]
ist jetzt erstmal so gelöst dass bei vornamen kürzer als 4 buchstaben eben weniger als 4 buchstaben rausgereicht werden.. Also Man Mustermann wird zu Max

**Comment by adedden** [comment]
Wenn Vorname weniger als 4 Zeichen, dann mit Leerzeichen
auffüllen.
