### ISSUE TITLE
"Eintrag Editieren" - Verpflichtete Felder

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#23]
Die Felder, die nicht leer bleiben dürfen, sind verpflichte Felder und sind in der Spalte D gekennzeichnet mit einem N. Noch nicht alle Felder sind entsprechend gekennzeichnet in der Ansicht für Sacharbeiter (z.B. Art der Registrierung als Promovierender oder Ende der Promotion - Monat und -Jahr.) Die soll in Fett mit einem roten Sternchen dargestellt werden.

**Comment by adedden** [comment]
Die Felder, die im Moment noch nicht richtig dargestellt sind: (müssen alle Fett mit Sternchen dargestellt werden)
- Geschlecht
- Geburtstag
- Vorname
- Nachname

**Comment by adedden** [comment]
Zusätzlich eine allgemeine Frage: werden die Felder nicht mehr als Pflichtfelder gekennzeichnet, so bald es eine Wert eingetragen ist?

**Comment by adedden** [comment]
Dieses Feld ist nur verplichtet, wenn HochschuleAbschlPr_lid = 2, sonnst darf es leer bleiben

**Comment by asudau** [comment]
welches Feld ist im letzten Kommentar gemeint?

**Comment by asudau** [comment]
die felder oben sind jetzt verpflictend markeirt wenn sie nicht ausgefüllt sind.. ansonsten wird das bei gelegenheit nochmal differenzierter dargestellt, dafür mach ich noch ein neues ticket auf..

**Comment by adedden** [comment]
Alle Feld anfängend mit StaatAbschlPr (gehören zur ef025)

**Comment by asudau** [comment]
hmm StaatAbschlPr (gehören zur ef025) ist aber schon als verpflichtend markiert..  
am besten ab jetzt für einzelne felder eigene tickets aufmachen, dann kann ich das besser zuordnen/abarbeiten..  
ich mach dieses ticket mal zu
