### ISSUE TITLE
Export nur in Admin-Übersicht zur Verfügung stellen

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#24]
Export nur in Admin-Übersicht zur Verfügung stellen: wäre schön, hat keine extrem hohe Priorität

**Comment by adedden** [comment]
nicht mehr benötigt

**Comment by adedden** [comment]
doch :)

**Comment by asudau** [comment]
das ist sehr fix gemacht, damit ihr ordentlich testen könnt mache ich das als allerletztes..

**Comment by asudau** [comment]
hab jetzt ne sonderregelung eingebaut, über abfrage der user_id, dass nur die user adedden und sudau@studip die exportfunktion sehen und ausführen können
