### ISSUE TITLE
Ich kann meinen angelegten Testfall nicht mehr bearbeiten!

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#25]
Hi Annelene,

Ich kann im Moment den von mir angelegten Testfall (Annemarie Dedden) überhaupt nicht mehr bearbeiten. Kannst du mal schauen was da los ist?

Danke dir :)

**Comment by asudau** [comment]
Das hat damit zu tun, dass es noch nicht zu allen Feldern die schlüsseltabellen gibt, zB Land.  
Dort soll ja zukünftig aus einer Auswahlliste gewählt werden und im HIntergrund dann die ID gespeichert werden.  
Habe das jetzt so gebaut, dass es erstmal nicht 'knallt' aber wenn man dort dann ein Land im Klartext eingibt ist das in der Datenbankt natürlich nicht korrekt hinterlegt auch wenn auf den ersten Blick alles gut aussieht, also nicht wundern ;-)  
D.h. wenn sich jemand über die Datenbankeinträge ander Stelle wunrder: das rüsten wir noch nach, so wie bei den anderen Such- und Dropdown-Feldern
