### ISSUE TITLE
Monatwerte: feste Eintragsmöglichkeiten

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#29]
damit gewährleistet werden kann, das Monate in dem richtigen Format ausgeführt werden, sollen die "monatsfelder" die mögliche Einträge: 01, 02, ... 12 enthälten

**Comment by adedden** [comment]
Dies betrifft die Felder: ef013u1 (Promotionsbeginn - Monat), ef014u1(Ende der Promotion - Monat), ef028 (Monat des Prüfungsabschlusses).

**Comment by asudau** [comment]
erledigt
