### ISSUE TITLE
Jahrwerte: feste Eintragsmöglichkeiten

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#30]
damit gewährleistet werden kann, das Jahre in dem richtigen Format ausgefüllt werden, sollen die "Jahrfelder" die mögliche Einträge: 2000, 2001... 2100 enthälten

**Comment by adedden** [comment]
Dies betrifft die Felder: ef013u2 (Promotionsbeginn - Jahr), ef014u2(Ende der Promotion - Jahr), ef022 (Jahr), ef029 (Jahr des Prüfungsabschlusses), ef031 (Jahr des Erwerbs einer HZB)

**Comment by asudau** [comment]
bin etwas unschlüssig die EIntrage reichen von 1969 oder so bis heute, da müsste ich ne ewig lange liste anlegen vermutlich wäre es besser wenn da ein Hinweis steht bzw. das Formular das Format prüft oder?   
Davon abgesehen ist das Jahr natürlich an sich eindeutiger als zB der Monat, da gibt es nich viel Spielraum :-P

**Comment by adedden** [comment]
Stimmt, guter Vorschlag! Mach es so :)

**Comment by asudau** [comment]
![grafik](https://user-images.githubusercontent.com/11834384/45880199-72528980-bda7-11e8-960e-95d21b2b86ec.png)

Wenn bei einem Jahres-Feld ein ungeeigneter Wert eingegeben wird wird dieser beim Speichern übersprungen und der Nutzer erhält eine Warnung
