### ISSUE TITLE
Fehlende Auswahlmöglichkeiten

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#31]
Für die folgende Felder fehlen die Auswahlmöglichkeiten noch:
- Staatsangehörigkeit (Umschlüsslungstabelle Country, siehe Übersicht der Spalten)
- weitere Staatsangehörigkeit (Umschlüsslungstabelle Country, siehe Übersicht der Spalten)
- Hochschule (Ersteinschreibung): (Umschlüsslungstabelle University, siehe Übersicht der Spalten)
- Bei Ersteinschreibung an einer Hochschule ausserhalb Deutschlands, der Staat der Hochschule: (Umschlüsslungstabelle Country, siehe Übersicht der Spalten)
- Art der ersten HZB: ... fehlt noch!! Muss ich (Anne) noch hinzufügen
- Art der ersten HZB - Bundesland, bzw.: (Umschlüsslungstabelle bundesländer, siehe Übersicht der Spalten)
- Art der ersten HZB - Kreis (bei Erwerb in Deutschland) bzw. Staat (bei Erwerb im Ausland): (Umschlüsslungstabelle Country und Landkreise DE, siehe Übersicht der Spalten)
- Hochschule: (Umschlüsslungstabelle University, siehe Übersicht der Spalten)
- Wenn Hochschule der zur Promotion berechtigenden, vorangegangenen bestandenen Abschlussprüfung außerhalb Deutschlands, der Staat der Hochschule: (Umschlüsslungstabelle Country, siehe Übersicht der Spalten)

**Comment by adedden** [comment]
Alle Felder aus Ticket #11 habe ich jetzt in dem Datenmodel hinzugefügt (und sind hier teilweise auch hier oben beschrieben). Das Datenmodel schicke ich per Email. Für ef016, ef017 und ef018 habe ich noch keine Umschlüsslung. Ich versuch die heute herauszufinden!

**Comment by asudau** [comment]
müssten jetzt alle drin sein, habe es jetzt vorerst so konfiguriert dass sie den astst_bund als schlüssel verwenden somit werden alle einträge für die vorhandenen datensätze korrekt aufgeschlüsselt.  
Sobald ich den angepassten export habe ändere ich einfach die Aufschlüsselung auf his_id/lid

**Comment by adedden** [comment]
Hi Annelene, sieht gut aus. Ich teste die Umschlüsslungen später allen nochmal einzel.
Es gibt 1 kleinere Änderung:
- ef017 hat sich geändert (siehe Übersicht der Spalten)

**Comment by adedden** [comment]
Hi Annelene, noch eine Anforderung in dieser Kategorie:
- Anstatt Art der ersten HZB - Kreis (bei Erwerb in Deutschland) bzw. Staat (bei Erwerb im Ausland) sollen die Variabelen HZBKreis_Standardtext und StaatHZB_Standtext in der Maske eingetragen werden. Diese Werte werden dann umgeschlüsselt nach ef033u2 für die Statistik

**Comment by adedden** [comment]
- definition von ef23 hat sich geändert (siehe Übersicht der Spalten)

**Comment by adedden** [comment]
- für gesamtnote soll jetzt auch feste Auswahlmöglichkeiten geben (siehe Mail mit Umschlüsslungstabelle "bewertung")

**Comment by asudau** [comment]
gesamtnote wird zu #54

**Comment by asudau** [comment]
ef023 status abschluss wird zu #55

**Comment by asudau** [comment]
ef017 wird zu #56
