### ISSUE TITLE
"Eintrag editieren" - Maske vergrößern

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#32]
Hi Annelene,

Kannst du die Maske vergrößern?
Es ist uns heute Morgen aufgefallen, dass beim Eintragen einer Uni, man die Optionen nicht allen sehen kann, weil die Maske "zu klein" ist.

Beste Grüße
Annemarie

**Comment by asudau** [comment]
ist ein ähnliches problem wie in #35 bzw. worde mit dem letzten commit dort hoffentlich verbessert

**Comment by adedden** [comment]
Sieht super aus so!
