### ISSUE TITLE
Erster Ansicht

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#33]
Kannst du bitte unter Promotionsfach Promotionsfach_Standardtext auswerten?

**Comment by adedden** [comment]
Hi Annelene, du wertest jetzt unter dem ersten Ansicht der Statistikschlüssel (ef011) aus. Es soll Promotionsfach_Standardtext, wie in der "Eintrag editieren"-Maske

**Comment by asudau** [comment]
ah ja verstehe, danke!
