### ISSUE TITLE
Auswahl der Studienfächer ist unübersichtlich

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#35]
z.B. wenn man Müns sucht, findet man nicht direkt Universität Münster. Kannst du mal schauen ob es hier eine schönere Lösung gibt? Wenn nicht, dann lassen wir es so

**Comment by asudau** [comment]
hmm, hier muss ich auch die suche noch verbessern

**Comment by adedden** [comment]
erledigt
