### ISSUE TITLE
Ende der Promotion (ef0141 und ef0142)

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#40]
Wenn unter Art der Registrierung als Promovierende (ef012), die Wert "Abbruch der Promotion", astat=06 und HIOID=3 oder "Abschluss der Promotion", astat=05 und HIOID=2, müssen hier Werte eingetragen werden (dürfen nicht leer bleiben).

Wenn hier keine Wert ausgefüllt wird von den Sacharbeitern, muss by default Monat=12 und das aktuelle Jahr ausgefüllt werden.

**Comment by adedden** [comment]
Gehört zu #47

**Comment by asudau** [comment]
die defaults müssen in dem moment eingetragen werden wenn das ganze exportiert wird  
wenn sich die anzahl der pflichtfelder dynamisch verhält wird das mit dem status anzeigen schwer - muss mal überlegen was mir dazu noch einfällt.. evtl. muss ich neben dem individuellen füllstand von jedem eintrag auch indidviduell angeben wieviele pflichfelder es für diesen eintrag gibt..

**Comment by adedden** [comment]
Hi Annelene, du hast Recht, die Umschlüsslung findet erst statt beim Export. Wenn die dynamische Pflichtfeldersetzung zu aufwendig ist, würde ich vorschlagen sie einfach keine Pflichtfelder zu machen.
