### ISSUE TITLE
Aktualisierte Schlüsseltabelle Studienform

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#41]
Hi Annelene,

Ich habe die Tabelle Studienform angepasst: defaulttext ist jetzt longtext und die "uniquename" habe ich rausgeschmissen. Ich habe dir gerade die CSV geschickt.

Gruß!!

**Comment by asudau** [comment]
bisherige Einträge löschen  
neue EInträge einspielen

**Comment by adedden** [comment]
Topp!
