### ISSUE TITLE
Zugriffsrechte checken

### ISSUE THREAD

**Issue by asudau** [asudau/Promovierendenverwaltung#42]
admin-plugin kann raus  
zugriffsberechtigung (zB beim Export) müssen geprüft werden  
$perm->check('admin');

**Comment by adedden** [comment]
Ich habe getestet für promovierenden_test.:

- Ich bekomme die richtige Promotionsfächer angezeigt. (Rechtswissenschaften und ohne Prom. Fach)
- Nur problematisch ist dass ich die Exports angezeigt bekomme und die sollen für Sacharbeiter nicht sichtbar sein (auch weil im Export nicht gefiltert wird nach Fachbereich)

**Comment by asudau** [comment]
huhu die exports nehm ich raus sobald wir produktiv gehen, das macht weniger arbeit als jetzt einzelne personen fürs testen zuzulassen..

**Comment by asudau** [comment]
rel #24
