### ISSUE TITLE
Plug-In Rolle zuordnen für User auf Produktiv

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#69]
Annemarie liefert Liste von User an

**Comment by sonschul** [comment]
[Fachbereiche.xlsx](https://github.com/asudau/Promovierendenverwaltung/files/2433081/Fachbereiche.xlsx)

Anbei die Liste der DekaneInnen, FachbereichsreferentInnen, BearbeiterInnen der Fachbereiche, die Zugang zur Doktorandenverwaltung bekommen sollten. (Stand 11.2017)

Besonderheit FB 3: Dort gibt es eine eigene Sachbearbeiterin für die Lehreinheit Kath. Theologie.

**Comment by asudau** [comment]
evtl brauch ihr hier elmars hilfe wenn ihr schon schulen wollt.. nutzer müssen zunächst die pluginrolle zugewiesen bekommen und dann zu dieser rollenzuweisung noch die einrichtung/ihren fachbereich zugeordnet bekommen

**Comment by sonschul** [comment]
Ich denke vor November wird keine Schulung mehr stattfinden. Bis dahin habe ich hoffentlich auch Antworten auf alle offenen Fragen von D7 z.B. Promotionsstudiengängen und Graduiertenkollegs.

**Comment by adedden** [comment]
[Alle User in HISinOne mit Rolle DoktMan.xlsx](https://github.com/asudau/Promovierendenverwaltung/files/2552377/Alle.User.in.HISinOne.mit.Rolle.DoktMan.xlsx)

**Comment by adedden** [comment]
[Alle Anwender für StudIP Plug-in.xlsx](https://github.com/asudau/Promovierendenverwaltung/files/2643830/Alle.Anwender.fur.StudIP.Plug-in.xlsx)

**Comment by adedden** [comment]
Soll am 10.12.2018 gemacht werden

**Comment by adedden** [comment]
[Alle Anwender für StudIP Plug-in_update 5.12.018.xlsx](https://github.com/asudau/Promovierendenverwaltung/files/2649117/Alle.Anwender.fur.StudIP.Plug-in_update.5.12.018.xlsx)
Es hat eine Aktualisierung gegeben, bitte diese Liste benutzen

**Comment by adedden** [comment]
Von Martin Gieseking erledigt worden
