### ISSUE TITLE
snapshot speichern

### ISSUE THREAD

**Issue by asudau** [asudau/Promovierendenverwaltung#7]
einfrieren eines aktuellen standes + möglichkeit diesen wieder auszuwählen + möglichkeit (nur ausgewählte nutzer) auch diesen noch nachzubearbeiten

**Comment by adedden** [comment]
Nach Rücksprache mit ZBW scheint dies wohl nicht unbedingt notwendig. Dieses Ticket können wir (zuerst) mal nicht bearbeiten
