### ISSUE TITLE
Eintragsmaske - Schlüssel weglassen

### ISSUE THREAD

**Issue by adedden** [asudau/Promovierendenverwaltung#86]
Geschlecht: Nur weiblich/männlich anzeigen, nicht 1 und 2
Immatrikuliert: nur ja/nein, kein 1/0
Beschäftigungsverhältnis: ja/nein, kein 1/0
Art der Dissertation: kein Schlüssel
Studienform: kein Schlüssel

**Comment by asudau** [comment]
ist angepasst
