### ISSUE TITLE
Bei "Art der Promotion" wenn möglich Langtext einblenden

### ISSUE THREAD

**Issue by asudau** [asudau/Promovierendenverwaltung#92]
hier fehlt mir offenbar die  tabelle k_type_of_doctorate um das zu aktualisieren also ich weiß gar nciht wie die long-texte aussehen sollten..

**Comment by adedden** [comment]
Ich schicke dir jetzt eine Email mit einem Update

**Comment by asudau** [comment]
super danke!

**Comment by asudau** [comment]
ist drin!
