### ISSUE TITLE
Bitte Auswahl überprüfen Promotionsfach

### ISSUE THREAD

**Issue by asudau** [asudau/Promovierendenverwaltung#93]
Bei Promotionsfach sind viele Fächer aufgeführt, die keine Promotionsfächer sind.

**Comment by adedden** [comment]
Ich meine, dass die Auswahlliste so stimmt. Kann gerne durch Sonja nochmal überprüft werden.

**Comment by asudau** [comment]
habe die Schlüsseltabellen jetzt beide nochmal aufgeräumt (promotionsfach und studienfach), müsste jetzt passen
