### ISSUE TITLE
Art der Dissertation - undefined 

### ISSUE THREAD

**Issue by sonschul** [asudau/Promovierendenverwaltung#94]
Die Auswahlmöglichkeit "undefiniert (von Migration)" entfernen.

**Comment by asudau** [comment]
das ist ein feld das aus dem his-in-one export mitkommt, wenn wir das nicht brauchen kann ich das gerne rauswerfen (die zugehörige his_id 99 taucht in den importierten datensätzen auch nicht auf..

**Comment by sonschul** [comment]
Meiner Meinung nach wird es nicht benötigt, weil es eine Pflichtangabe ist und die Option "undefined" nicht möglich ist.

**Comment by asudau** [comment]
alles klar ich nehm es raus!
